Add a useless declaration to every output file.
tiziano88/elm-protobuf pull request #25
Opened 2019-04-07 21:35 UTC by EdSchouten

Without this declaration in place, we may end up source files that are
not buildable by Elm. Elm requires that all source files contain at
least one declaration.

An example of a source file that contains no declarations is part of
Google APIs:

https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto

This file is transitively dragged in by Bazel's remote execution
defintions:

https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto

2019-04-08 09:48 UTC, tiziano88 requested changes
Thanks, this makes sense, could you also fix the tests so that they keep passing? :)

2019-04-08 09:48 UTC, tiziano88 commented on protoc-gen-elm/main.go
> +	fg.P("")
Probably move this to the top of the file (after the imports) rather than the bottom?

2019-04-09 07:48 UTC, EdSchouten commented
> Thanks, this makes sense, could you also fix the tests so that they keep passing? :)

Done!

2019-04-09 10:37 UTC, tiziano88 approved these changes

2019-04-09 10:38 UTC, merged